StartupEvents.registry('block', event => {

    event.create('astrogreg:futura_alloy_casing')
        .translationKey('block.astrogreg.futura_alloy_casing')
        .hardness(6)
        .resistance(3)
        .soundType('metal')
        .requiresTool(true)
        .mapColor('terracotta_magenta')
        .tagBlock('mineable/pickaxe_or_wrench')
        .tagBlock('minecraft:needs_iron_tool')
        .textureAll('kubejs:block/casings/futura_assembler_casing')
		.fullBlock(true)
		.opaque(true)

    event.create('astrogreg:livingbricks')
        .translationKey('block.astrogreg.livingbricks')
        .hardness(0.8)
        .resistance(0.8)
        .soundType('stone')
        .requiresTool(true)
        .mapColor('terracotta_light_gray')
        .tagBlock('mineable/pickaxe')
        .textureAll('kubejs:block/bricks/livingbricks')
		.fullBlock(true)
        .opaque(true)

    event.create('botania:managlass')
        .translationKey('block.astrogreg.managlass')
		.hardness(5)
		.resistance(2)
		.soundType('glass')
		.tagBlock('gtceu:mineable/pickaxe_or_wrench')
        .tagBoth('c:glass_blocks')
		.mapColor('color_light_blue')
        .textureAll('kubejs:block/glass/managlass')
		.defaultTranslucent()
    
    event.create('botania:alfglass')
        .translationKey('block.astrogreg.alfglass')
		.hardness(5)
		.resistance(2)
		.soundType('glass')
		.tagBlock('gtceu:mineable/pickaxe_or_wrench')
        .tagBoth('c:glass_blocks')
		.mapColor('color_light_blue')
        .textureAll('kubejs:block/glass/alfglass')
		.defaultTranslucent()
})