StartupEvents.registry('block', event => {

    event.create('gtceu:futura_casing')
        .displayName('Futura Casing')
        .hardness(6)
        .resistance(3)
        .soundType('metal')
        .requiresTool(true)
        .mapColor('terracotta_magenta')
        .tagBlock('mineable/pickaxe')
        .tagBlock('mineable/wrench')
        .tagBlock('minecraft:needs_iron_tool')
        .textureAll('kubejs:block/casings/futura_assembler_casing')
		.fullBlock(true)
		.opaque(true)

    event.create('gtceu:manasteel_machine_casing')
        .displayName('Manasteel Plated Brick Casing')
        .hardness(5)
        .resistance(2)
        .soundType('metal')
        .requiresTool(true)
        .mapColor('terracotta_light_blue')
        .tagBlock('mineable/pickaxe')
        .tagBlock('mineable/wrench')
        .tagBlock('minecraft:needs_stone_tool')
        .textureAll('kubejs:block/casings/machine_casing_manasteel_plated_bricks')
        .fullBlock(true)
        .opaque(true)

    event.create('gtceu:manasteel_firebox_casing', 'gtceu:active')
        .displayName('Manasteel Firebox Casing')
        .firebox('kubejs:block/casings/machine_casing_manasteel_plated_bricks',
            "kubejs:block/casings/machine_casing_firebox_manasteel",
            'kubejs:block/casings/machine_casing_manasteel_plated_bricks')
        .hardness(5)
        .resistance(2)
        .soundType('metal')
        .requiresTool(true)
        .mapColor('terracotta_blue')		
        .tagBlock('gtceu:mineable/pickaxe_or_wrench')
        .tagBlock('minecraft:needs_stone_tool')
        .fullBlock(true)
        .opaque(true)

    event.create('gtceu:livingbricks')
        .displayName('Livingbricks')
        .hardness(0.8)
        .resistance(0.8)
        .soundType('stone')
        .requiresTool(true)
        .mapColor('terracotta_light_gray')
        .tagBlock('mineable/pickaxe')
        .textureAll('kubejs:block/bricks/livingbricks')
		.fullBlock(true)
        .opaque(true)

    event.create('botania:managlass')
        .displayName('Mana Glass')
		.hardness(5)
		.resistance(2)
		.soundType('glass')
		.tagBlock('gtceu:mineable/pickaxe_or_wrench')
        .tagBoth('c:glass_blocks')
		.mapColor('color_light_blue')
        .textureAll('kubejs:block/glass/managlass')
		.defaultTranslucent()
    
    event.create('botania:alfglass')
        .displayName('Elven Glass')
		.hardness(5)
		.resistance(2)
		.soundType('glass')
		.tagBlock('gtceu:mineable/pickaxe_or_wrench')
        .tagBoth('c:glass_blocks')
		.mapColor('color_light_blue')
        .textureAll('kubejs:block/glass/alfglass')
		.defaultTranslucent()

    event.create('gtceu:solid_terrasteel_casing')
        .displayName('Solid Terrasteel Casing')
        .hardness(6)
        .resistance(3)
        .soundType('metal')
        .requiresTool(true)
        .mapColor('color_green')
		.tagBlock('gtceu:mineable/pickaxe_or_wrench')
        .tagBlock('minecraft:needs_iron_tool')
        .textureAll('kubejs:block/casings/terrasteel_casing')
		.fullBlock(true)
		.opaque(true)

    event.create('gtceu:alfsteel_turbine_casing')
        .displayName('Alfsteel Turbine Casing')
        .hardness(6)
        .resistance(3)
        .soundType('metal')
        .requiresTool(true)
        .mapColor('color_pink')
		.tagBlock('gtceu:mineable/pickaxe_or_wrench')
        .tagBlock('minecraft:needs_iron_tool')
        .textureAll('kubejs:block/casings/machine_casing_turbine_alfsteel')
		.fullBlock(true)
		.opaque(true)    
})