GTCEuStartupEvents.registry('gtceu:dimension_marker', event => {
    event.create('ad_astra:kuiper_belt')
        .iconSupplier(() => Item.of('gtceu:asteroid_stone').getItem())
        .tier(0)
        .overrideName('Kuiper Belt')
    // event.create('minecraft:overworld')
    //     .iconSupplier(() => Item.of('ad_astra:earth_globe'))
    //     .tier(0)
    //     .overrideName('Earth')
    event.create('ad_astra:moon')
        .iconSupplier(() => Item.of('ad_astra:moon_globe').getItem())
        .tier(0)
        .overrideName('Moon')
    event.create('ad_astra:mars')
        .iconSupplier(() => Item.of('ad_astra:mars_globe').getItem())
        .tier(0)
        .overrideName('Mars')
    event.create('ad_astra:mercury')
        .iconSupplier(() => Item.of('ad_astra:mercury_globe').getItem())
        .tier(0)
        .overrideName('Mercury')
    event.create('ad_astra:venus')
        .iconSupplier(() => Item.of('ad_astra:venus_globe').getItem())
        .tier(0)
        .overrideName('Venus')   
    event.create('ad_extendra:ceres')
        .iconSupplier(() => Item.of('ad_extendra:ceres_globe').getItem())
        .tier(0)
        .overrideName('Ceres')   
    event.create('ad_extendra:jupiter')
        .iconSupplier(() => Item.of('ad_extendra:jupiter_globe').getItem())
        .tier(0)
        .overrideName('Jupiter')   
    event.create('ad_extendra:saturn')
        .iconSupplier(() => Item.of('ad_extendra:saturn_globe').getItem())
        .tier(0)
        .overrideName('Saturn')   
    event.create('ad_extendra:uranus')
        .iconSupplier(() => Item.of('ad_extendra:uranus_globe').getItem())
        .tier(0)
        .overrideName('Uranus')   
    event.create('ad_extendra:neptune')
        .iconSupplier(() => Item.of('ad_extendra:neptune_globe').getItem())
        .tier(0)
        .overrideName('Neptune')   
    event.create('ad_extendra:pluto')
        .iconSupplier(() => Item.of('ad_extendra:pluto_globe').getItem())
        .tier(0)
        .overrideName('Pluto')
})