ClientEvents.lang('en_us', event => {
//#region botania
event.renameItem('botania:elementium_sword', '§dAlfsteel§r Sword')
event.renameItem('botania:elementium_hoe', '§dAlfsteel§r Hoe')
event.renameItem('botania:elementium_axe', '§dAlfsteel§r Axe')
event.renameItem('botania:elementium_shovel', '§dAlfsteel§r Shovel')
event.renameItem('botania:elementium_pickaxe', '§dAlfsteel§r Pickaxe')
event.renameItem('botania:elementium_boots', '§dAlfsteel§r Boots')
event.renameItem('botania:elementium_leggings', '§dAlfsteel§r Leggings')
event.renameItem('botania:elementium_chestplate', '§dAlfsteel§r Chestplate')
event.renameItem('botania:elementium_helmet', '§dAlfsteel§r Helmet')
event.renameItem('botania:elementium_shears', '§dAlfsteel§r Shears')
event.renameItem('botania:elementium_nugget', '§dAlfsteel§r Nugget')
event.renameItem('botania:elementium_ingot', '§dAlfsteel§r Ingot')
event.renameItem('botania:elementium_block', '§dAlfsteel§r Block')
event.renameItem('botania:manasteel_sword', '§9Manasteel§r Sword')
event.renameItem('botania:manasteel_hoe', '§9Manasteel§r Hoe')
event.renameItem('botania:manasteel_axe', '§9Manasteel§r Axe')
event.renameItem('botania:manasteel_shovel', '§9Manasteel§r Shovel')
event.renameItem('botania:manasteel_pick', '§9Manasteel§r Pickaxe')
event.renameItem('botania:manasteel_boots', '§9Manasteel§r Boots')
event.renameItem('botania:manasteel_leggings', '§9Manasteel§r Leggings')
event.renameItem('botania:manasteel_chestplate', '§9Manasteel§r Chestplate')
event.renameItem('botania:manasteel_helmet', '§9Manasteel§r Helmet')
event.renameItem('botania:manasteel_shears', '§9Manasteel§r Shears')
event.renameItem('botania:manasteel_nugget', '§9Manasteel§r Nugget')
event.renameItem('botania:manasteel_ingot', '§9Manasteel§r Ingot')
event.renameItem('botania:manasteel_block', '§9Manasteel§r Block')
event.renameItem('botania:terrasteel_boots', '§2Terrasteel§r Boots')
event.renameItem('botania:terrasteel_leggings', '§2Terrasteel§r Leggings')
event.renameItem('botania:terrasteel_chestplate', '§2Terrasteel§r Chestplate')
event.renameItem('botania:terrasteel_helmet', '§2Terrasteel§r Helmet')
event.renameItem('botania:terrasteel_shears', '§2Terrasteel§r Shears')
event.renameItem('botania:terrasteel_nugget', '§2Terrasteel§r Nugget')
event.renameItem('botania:terrasteel_ingot', '§2Terrasteel§r Ingot')
event.renameItem('botania:terrasteel_block', '§2Terrasteel§r Block')
event.renameItem('botania:gaia_pylon', '§dElven Pylon§r')
})