ClientEvents.lang('en_us', event => {
//#region botania
event.renameItem('botania:elementium_sword', '§dAlfsteel§r Sword')
event.renameItem('botania:elementium_hoe', '§dAlfsteel§r Hoe')
event.renameItem('botania:elementium_axe', '§dAlfsteel§r Axe')
event.renameItem('botania:elementium_shovel', '§dAlfsteel§r Shovel')
event.renameItem('botania:elementium_pickaxe', '§dAlfsteel§r Pickaxe')
event.renameItem('botania:elementium_boots', '§dAlfsteel§r Boots')
event.renameItem('botania:elementium_leggings', '§dAlfsteel§r Leggings')
event.renameItem('botania:elementium_chestplate', '§dAlfsteel§r Chestplate')
event.renameItem('botania:elementium_helmet', '§dAlfsteel§r Helmet')
event.renameItem('botania:elementium_shears', '§dAlfsteel§r Shears')
event.renameItem('botania:elementium_nugget', '§dAlfsteel§r Nugget')
event.renameItem('botania:elementium_ingot', '§dAlfsteel§r Ingot')
event.renameItem('botania:elementium_block', '§dAlfsteel§r Block')
event.renameItem('botania:manasteel_sword', '§9Manasteel§r Sword')
event.renameItem('botania:manasteel_hoe', '§9Manasteel§r Hoe')
event.renameItem('botania:manasteel_axe', '§9Manasteel§r Axe')
event.renameItem('botania:manasteel_shovel', '§9Manasteel§r Shovel')
event.renameItem('botania:manasteel_pick', '§9Manasteel§r Pickaxe')
event.renameItem('botania:manasteel_boots', '§9Manasteel§r Boots')
event.renameItem('botania:manasteel_leggings', '§9Manasteel§r Leggings')
event.renameItem('botania:manasteel_chestplate', '§9Manasteel§r Chestplate')
event.renameItem('botania:manasteel_helmet', '§9Manasteel§r Helmet')
event.renameItem('botania:manasteel_shears', '§9Manasteel§r Shears')
event.renameItem('botania:manasteel_nugget', '§9Manasteel§r Nugget')
event.renameItem('botania:manasteel_ingot', '§9Manasteel§r Ingot')
event.renameItem('botania:manasteel_block', '§9Manasteel§r Block')
event.renameItem('botania:terrasteel_boots', '§2Terrasteel§f Boots')
event.renameItem('botania:terrasteel_leggings', '§2Terrasteel§f Leggings')
event.renameItem('botania:terrasteel_chestplate', '§2Terrasteel§f Chestplate')
event.renameItem('botania:terrasteel_helmet', '§2Terrasteel§f Helmet')
event.renameItem('botania:terrasteel_shears', '§2Terrasteel§f Shears')
event.renameItem('botania:terrasteel_nugget', '§2Terrasteel§f Nugget')
event.renameItem('botania:terrasteel_ingot', '§2Terrasteel§f Ingot')
event.renameItem('botania:terrasteel_block', '§2Terrasteel§f Block')
event.renameItem('botania:gaia_pylon', '§dElven Pylon§r')
event.renameItem('botania:mana_pylon', '§bMana Pylon§r')
event.renameItem('botania:mana_pylon', '§2Natura Pylon§r')
//#endregion

//#region gregtech
event.renameItem('gtmutils:neutronium_credit', '§cAstroCredit')
event.renameItem('gtceu:lv_power_unit', '§7Low Power Unit')
event.renameItem('gtceu:mv_power_unit', '§bMedium Power Unit')
event.renameItem('gtceu:hv_power_unit', '§6High Power Unit')
event.renameItem('gtceu:ev_power_unit', '§5Extreme Power Unit')
event.renameItem('gtceu:iv_power_unit', '§9Insane Power Unit')
event.renameItem('gtmutils:luv_power_unit', '§dLudicrous Power Unit')
event.renameItem('gtmutils:zpm_power_unit', '§cZero Point Power Unit')
event.renameItem('gtceu:iv_parallel_hatch', '§9Basic Parallel Control Hatch')
event.renameItem('gtceu:luv_parallel_hatch', '§dAdvanced Parallel Control Hatch')
event.renameItem('gtceu:zpm_parallel_hatch', '§cElite Parallel Control Hatch')
event.renameItem('gtceu:uv_parallel_hatch', '§3Ultimate Parallel Control Hatch')
//#endregion

//#region ad astra
event.renameItem('ad_astra:wheel', 'Rubber Tire')
event.renameItem('ad_astra:launch_pad', 'Rocket Launch Platform')
event.renameItem('ad_astra:tier_1_rocket', '§bASTRO-Falcon')
event.renameItem('ad_astra:tier_2_rocket', '§6ASTRO-Falcon II')
event.renameItem('ad_astra:tier_3_rocket', '§5ASTRO-Pegasus')
event.renameItem('ad_astra:tier_4_rocket', '§9ASTRO-Pegasus II')
event.renameItem('ad_extendra:tier_5_rocket', '§dASTRO-Thunderbird')
event.renameItem('ad_extendra:tier_6_rocket', '§cASTRO-Thunderbird II')
event.renameItem('ad_extendra:tier_7_rocket', '§3ASTRO-Thunderbird III')
event.renameItem('ad_extendra:tier_8_rocket', '§4ASTRO-Atlas')
event.renameItem('ad_astra:tier_1_rover', '§bASTRO-Scarab')
//#endregion

//region simply light
event.renameItem('simplylight:illuminant_block_on', 'Illuminant Block (On)')
event.renameItem('simplylight:illuminant_light_gray_block_on', 'Illuminant Light Gray Block (On)')
event.renameItem('simplylight:illuminant_gray_block_on', 'Illuminant Gray Block (On)')
event.renameItem('simplylight:illuminant_black_block_on', 'Illuminant Black Block (On)')
event.renameItem('simplylight:illuminant_brown_block_on', 'Illuminant Brown Block (On)')
event.renameItem('simplylight:illuminant_red_block_on', 'Illuminant Red Block (On)')
event.renameItem('simplylight:illuminant_yellow_block_on', 'Illuminant Yellow Block (On)')
event.renameItem('simplylight:illuminant_lime_block_on', 'Illuminant Lime Block (On)')
event.renameItem('simplylight:illuminant_green_block_on', 'Illuminant Green Block (On)')
event.renameItem('simplylight:illuminant_cyan_block_on', 'Illuminant Cyan Block (On)')
event.renameItem('simplylight:illuminant_light_blue_block_on', 'Illuminant Light Blue Block (On)')
event.renameItem('simplylight:illuminant_blue_block_on', 'Illuminant Blue Block (On)')
event.renameItem('simplylight:illuminant_purple_block_on', 'Illuminant Purple Block (On)')
event.renameItem('simplylight:illuminant_magenta_block_on', 'Illuminant Magenta Block (On)')
event.renameItem('simplylight:illuminant_pink_block_on', 'Illuminant Pink Block (On)')
event.renameItem('simplylight:lamp_post', 'Illuminant Lamp Post')
//#endregion

//region misc
event.renameItem('powah:steel_energized', 'Energized Steel Ingot')
})