ServerEvents.recipes(event => {

    event.remove({ id: 'gtceu:research_station/1x_gtceu_me_pattern_buffer' })
    event.remove({ id: 'gtceu:scanner/1_x_gtceu_luv_dual_input_hatch' })
    event.remove({ id: 'gtceu:research_station/1x_gtceu_zpm_dual_input_hatch' })
    event.remove({ id: 'gtceu:assembly_line/expanded_me_pattern_buffer' })
    event.remove({ id: 'gtceu:research_station/1x_gtceu_me_pattern_buffer_proxy' })
    event.remove({ id: 'gtceu:assembly_line/expanded_me_buffer_proxy' })
    event.remove({ id: 'gtceu:assembly_line/me_pattern_buffer' })
    event.remove({ id: 'gtceu:assembly_line/me_pattern_buffer_proxy' })

    event.recipes.gtceu.assembly_line('me_pattern_buffer_proxy')
        .itemInputs('gtceu:me_pattern_buffer')
        .itemInputs('gtceu:luv_sensor')
        .itemInputs('gtceu:luv_emitter')
        .itemInputs('#gtceu:circuits/luv')
        .itemInputs('expatternprovider:ex_pattern_provider')
        .itemInputs('expatternprovider:wireless_connect')
        .itemInputs('48x gtceu:fine_indium_tin_barium_titanium_cuprate_wire')
        .inputFluids('gtceu:soldering_alloy 576')
        .itemOutputs('gtceu:me_pattern_buffer_proxy')
        .duration(600)
        .EUt(30720)
        .addMaterialInfo(true)
        ['scannerResearch(java.util.function.UnaryOperator)']
            (b => b
                .researchStack('gtceu:me_pattern_buffer')
                .duration(1200)
                .EUt(7680)
            )

    event.recipes.gtceu.assembly_line('expanded_me_pattern_buffer_proxy')
        .itemInputs('gtmutils:expanded_me_pattern_buffer')
        .itemInputs('gtceu:zpm_sensor')
        .itemInputs('gtceu:zpm_emitter')
        .itemInputs('#gtceu:circuits/zpm')
        .itemInputs('expandedae:exp_pattern_provider')
        .itemInputs('4x expatternprovider:wireless_connect')
        .itemInputs('64x gtceu:fine_uranium_rhodium_dinaquadide_wire')
        .itemInputs('32x gtceu:fine_uranium_rhodium_dinaquadide_wire')
        .inputFluids('gtceu:soldering_alloy 576')
        .itemOutputs('gtmutils:expanded_me_pattern_buffer_proxy')
        .duration(600)
        .EUt(122880)
        .addMaterialInfo(true)
        .stationResearch(
            researchRecipeBuilder => researchRecipeBuilder
                .researchStack(Item.of(`gtmutils:expanded_me_pattern_buffer`))
                .dataStack('gtceu:data_orb')
                .CWUt(48, 128000)
                .EUt(30720)
        )

    event.recipes.gtceu.assembly_line('me_pattern_buffer')
        .itemInputs('gtceu:luv_machine_hull')
        .itemInputs('2x gtceu:luv_conveyor_module')
        .itemInputs('2x #gtceu:circuits/luv')
        .itemInputs('expatternprovider:ex_pattern_provider')
        .itemInputs('4x ae2:speed_card')
        .itemInputs('2x gtceu:niobium_titanium_single_cable')
        .inputFluids('gtceu:soldering_alloy 576')
        .itemOutputs('gtceu:me_pattern_buffer')
        .duration(600)
        .EUt(30720)
        .addMaterialInfo(true)
        ['scannerResearch(java.util.function.UnaryOperator)']
            (b => b
                .researchStack('expatternprovider:ex_pattern_provider')
                .duration(1200)
                .EUt(7680)
            )

    event.recipes.gtceu.assembly_line('expanded_me_pattern_buffer')
        .itemInputs('gtceu:zpm_machine_hull')
        .itemInputs('2x gtceu:zpm_conveyor_module')
        .itemInputs('2x #gtceu:circuits/zpm')
        .itemInputs('expandedae:exp_pattern_provider')
        .itemInputs('4x ae2:speed_card')
        .itemInputs('2x gtceu:vanadium_gallium_single_cable')
        .inputFluids('gtceu:soldering_alloy 576')
        .itemOutputs('gtmutils:expanded_me_pattern_buffer')
        .duration(600)
        .EUt(122880)
        .addMaterialInfo(true)
        .stationResearch(
            researchRecipeBuilder => researchRecipeBuilder
                .researchStack(Item.of('expandedae:exp_pattern_provider'))
                .dataStack('gtceu:data_orb')
                .CWUt(32, 132000)
                .EUt(30720)
        )
})