ServerEvents.recipes(event => {

    event.recipes.gtceu.assembler('iv_parallel_hatch')
        .itemInputs('4x #gtceu:circuits/luv', 'gtceu:tungsten_carbide_frame', '6x gtceu:double_tungsten_steel_plate',
            'gtceu:iv_sensor', 'gtceu:iv_emitter', '4x gtceu:platinum_double_cable')
        .inputFluids('gtceu:soldering_alloy 576')
        .itemOutputs('gtceu:iv_parallel_hatch')
        .duration(400)
        .EUt(6000)
        .addMaterialInfo(true)

    event.recipes.gtceu.assembly_line('luv_parallel_hatch')
        .itemInputs('4x #gtceu:circuits/zpm')
        .itemInputs('gtceu:ruridit_frame')
        .itemInputs('6x gtceu:double_rhodium_plated_palladium_plate')
        .itemInputs('2x gtceu:luv_sensor')
        .itemInputs('2x gtceu:luv_emitter')
        .itemInputs('gtceu:luv_field_generator')
        .itemInputs('4x gtceu:niobium_titanium_double_cable')
        .inputFluids('gtceu:soldering_alloy 576')
        .inputFluids('gtceu:polytetrafluoroethylene 576')
        .itemOutputs('gtceu:luv_parallel_hatch')
        .duration(400)
        .EUt(24000)
        .addMaterialInfo(true)
        ["scannerResearch(java.util.function.UnaryOperator)"]
        (b => b
            .researchStack("gtceu:iv_parallel_hatch")
            .duration(1800)
            .EUt(6000)
        )    
        
    event.recipes.gtceu.assembly_line('zpm_parallel_hatch')
        .itemInputs('4x #gtceu:circuits/uv')
        .itemInputs('gtceu:naquadah_alloy_frame')
        .itemInputs('6x gtceu:double_naquadah_alloy_plate')
        .itemInputs('2x gtceu:zpm_sensor')
        .itemInputs('2x gtceu:zpm_emitter')
        .itemInputs('gtceu:zpm_field_generator')
        .itemInputs('4x gtceu:vanadium_gallium_double_cable')
        .inputFluids('gtceu:soldering_alloy 576')
        .inputFluids('gtceu:polybenzimidazole 576')
        .itemOutputs('gtceu:zpm_parallel_hatch')
        .duration(400)
        .EUt(96000)
        .addMaterialInfo(true)
        .stationResearch(
            researchRecipeBuilder => researchRecipeBuilder
                .researchStack(Item.of(`gtceu:luv_parallel_hatch`))
                .dataStack('gtceu:data_orb')
                .CWUt(16, 96000)
                .EUt(30720)
        )

    event.recipes.gtceu.assembly_line('uv_parallel_hatch')
        .itemInputs('4x #gtceu:circuits/uhv')
        .itemInputs('gtceu:tritanium_frame')
        .itemInputs('6x gtceu:double_darmstadtium_plate')
        .itemInputs('2x gtceu:uv_sensor')
        .itemInputs('2x gtceu:uv_emitter')
        .itemInputs('gtceu:uv_field_generator')
        .itemInputs('4x gtceu:yttrium_barium_cuprate_double_cable')
        .inputFluids('gtceu:soldering_alloy 576')
        .inputFluids('gtceu:polybenzimidazole 1152')
        .itemOutputs('gtceu:uv_parallel_hatch')
        .duration(400)
        .EUt(384000)
        .addMaterialInfo(true)
        .stationResearch(
            researchRecipeBuilder => researchRecipeBuilder
                .researchStack(Item.of(`gtceu:zpm_parallel_hatch`))
                .dataStack('gtceu:data_module')
                .CWUt(48, 128000)
                .EUt(122880)
        )

    event.recipes.gtceu.assembly_line('uhv_parallel_hatch')
        .itemInputs('8x #gtceu:circuits/uhv')
        .itemInputs('gtceu:neutronium_frame')
        .itemInputs('6x gtceu:double_neutronium_plate')
        .itemInputs('4x gtceu:uv_sensor')
        .itemInputs('4x gtceu:uv_emitter')
        .itemInputs('2x gtceu:uv_field_generator')
        .itemInputs('4x gtceu:europium_double_cable')
        .inputFluids('gtceu:soldering_alloy 576')
        .inputFluids('astrogreg:polyamide_imide 1152')
        .itemOutputs('astrogreg:uhv_parallel_hatch')
        .duration(400)
        .EUt(1536000)
        .addMaterialInfo(true)
        .stationResearch(
            researchRecipeBuilder => researchRecipeBuilder
                .researchStack(Item.of(`gtceu:zpm_parallel_hatch`))
                .dataStack('gtceu:data_module')
                .CWUt(144, 256000)
                .EUt(122880)
        )    
})