ServerEvents.recipes(event => {
    //replace

    //#region input
    event.replaceInput({input: 'create:copper_sheet'}, 'create:copper_sheet', 'gtceu:copper_plate')
    event.replaceInput({input: 'create:zinc_ingot'}, 'create:zinc_ingot', 'gtceu:zinc_ingot')
    event.replaceInput({}, 'botania:redstone_root', 'gtceu:red_alloy_dust')
    event.replaceInput({}, 'ad_astra:steel_rod', 'gtceu:steel_rod')
    event.replaceInput({}, 'ad_astra:iron_rod', 'gtceu:iron_rod')
    event.replaceInput({}, 'minecraft:gravel', '#forge:gravel')
    event.replaceInput({}, 'minecraft:sand', '#minecraft:smelts_to_glass')
    event.replaceInput({id: 'farmersdelight:roast_chicken_block'}, '#forge:eggs', 'farmersdelight:fried_egg')
    event.replaceInput({id: 'delightful:food/pumpkin_pie'}, '#forge:eggs', 'farmersdelight:fried_egg')
    event.replaceInput({input: 'botania:rune_fire'}, 'botania:rune_fire', 'botania:fire_rune')
    event.replaceInput({input: 'botania:rune_water'}, 'botania:rune_water', 'botania:water_rune')
    event.replaceInput({input: 'botania:rune_air'}, 'botania:rune_air', 'botania:air_rune')
    event.replaceInput({input: 'botania:rune_earth'}, 'botania:rune_earth', 'botania:earth_rune')
    event.replaceInput({input: 'botania:rune_spring'}, 'botania:rune_spring', 'botania:spring_rune')
    event.replaceInput({input: 'botania:rune_summer'}, 'botania:rune_summer', 'botania:summer_rune')
    event.replaceInput({input: 'botania:rune_autumn'}, 'botania:rune_autumn', 'botania:autumn_rune')
    event.replaceInput({input: 'botania:rune_winter'}, 'botania:rune_winter', 'botania:winter_rune')
    event.replaceInput({input: 'botania:rune_mana'}, 'botania:rune_mana', 'botania:mana_rune')
    event.replaceInput({input: 'botania:rune_greed'}, 'botania:rune_greed', 'botania:greed_rune')
    event.replaceInput({input: 'botania:rune_wrath'}, 'botania:rune_wrath', 'botania:wrath_rune')
    event.replaceInput({input: 'botania:rune_pride'}, 'botania:rune_pride', 'botania:pride_rune')
    event.replaceInput({input: 'botania:rune_lust'}, 'botania:rune_lust', 'botania:lust_rune')
    event.replaceInput({input: 'botania:rune_sloth'}, 'botania:rune_sloth', 'botania:sloth_rune')
    event.replaceInput({input: 'botania:rune_gluttony'}, 'botania:rune_gluttony', 'botania:gluttony_rune')
    event.replaceInput({input: 'botania:rune_envy'}, 'botania:rune_envy', 'botania:envy_rune')
    event.replaceInput({output: 'minecraft:brick'}, 'minecraft:clay_ball', 'gtceu:compressed_clay')
    event.replaceInput({output: /gtceu:lv_.*/}, 'minecraft:diamond', 'gtceu:grinding_head_damascus_steel')
    event.replaceInput({output: /gtceu:mv_.*/}, 'minecraft:diamond', 'gtceu:grinding_head_damascus_steel')
    event.replaceInput({output: /gtceu:zpm_.*/}, 'gtceu:tungsten_grinding_head', 'gtceu:grinding_head_duranium')
    event.replaceInput({output: /gtceu:uv_.*/}, 'gtceu:tungsten_grinding_head', 'gtceu:grinding_head_duranium')
    event.replaceInput({}, 'gtceu:diamond_grinding_head', 'gtceu:grinding_head_diamond')
    event.replaceInput({}, 'gtceu:tungsten_grinding_head', 'gtceu:grinding_head_tungsten')
    event.replaceInput({}, 'botania:mana_glass', 'botania:managlass')
    event.replaceInput({}, 'botania:elf_glass', 'botania:alfglass')
    event.replaceInput({}, 'ad_extendra:saturlyte_ingot', 'astrogreg:saturlyte_ingot')
    event.replaceInput({}, 'ad_extendra:juperium_ingot', 'astrogreg:juperium_ingot')
    event.replaceInput({output: 'farmersdelight:mixed_salad'}, 'farmersdelight:tomato', 'farmersdelight:tomato_slice')
    event.replaceInput({output: 'farmersdelight:fruit_salad'}, 'minecraft:apple', 'farmersdelight:apple_slice')
    event.replaceInput({output: 'farmersdelight:bacon_sandwich'}, 'farmersdelight:tomato', 'farmersdelight:tomato_slice')
    event.replaceInput({output: 'farmersdelight:hamburger'}, 'farmersdelight:tomato', 'farmersdelight:tomato_slice')
    event.replaceInput({output: 'delightful:cheeseburger'}, 'farmersdelight:tomato', 'farmersdelight:tomato_slice')
    event.replaceInput({output: 'delightful:deluxe_cheeseburger'}, 'farmersdelight:tomato', 'farmersdelight:tomato_slice')
    event.replaceInput({output: 'gtceu:ev_hermetic_casing'}, 'gtceu:stainless_steel_large_fluid_pipe', 'gtceu:tungsten_carbide_large_fluid_pipe')
    event.replaceInput({output: 'gtceu:iv_hermetic_casing'}, 'gtceu:titanium_large_fluid_pipe', 'gtceu:osmiridium_large_item_pipe')
    event.replaceInput({output: 'gtceu:luv_hermetic_casing'}, 'gtceu:tungsten_steel_large_fluid_pipe', 'gtceu:polybenzimidazole_large_fluid_pipe')
    event.replaceInput({output: 'gtceu:uv_hermetic_casing'}, 'gtceu:naquadah_large_fluid_pipe', 'gtceu:duranium_large_fluid_pipe')
    event.replaceInput({output: 'gtceu:uhv_hermetic_casing'}, 'gtceu:duranium_large_fluid_pipe', 'astrogreg:polyamide_imide_large_fluid_pipe')
    event.replaceInput({}, '#forge:crops/cabbage', 'farmersdelight:cabbage_leaf')
    event.replaceInput({type: 'gtceu:mixer'}, 'gtceu:stone_dust', '#forge:stone_dust')
    event.replaceInput({type: 'gtceu:compressor'}, 'gtceu:stone_dust', '#forge:stone_dust')
    event.replaceInput({output: 'megacells:bulk_cell_component'}, 'ae2:sky_dust', 'gtceu:netherite_dust')
    event.replaceInput({output: 'megacells:bulk_item_cell'}, 'ae2:sky_dust', 'gtceu:dense_netherite_plate')
    event.replaceInput({output: 'megacells:bulk_item_cell'}, 'minecraft:netherite_ingot', 'astrogreg:dense_futura_alloy_plate')
    event.replaceInput({id: 'gtceu:assembly_line/conveyor_module_luv'}, 'gtceu:hsss_plate', 'gtceu:hsss_sleeve')
    event.replaceInput({id: 'gtceu:assembly_line/electric_piston_luv'}, 'gtceu:hsss_rod', 'gtceu:hsss_sleeve')
    event.replaceInput({id: 'gtceu:assembly_line/conveyor_module_zpm'}, 'gtceu:osmiridium_plate', 'gtceu:duranium_sleeve')
    event.replaceInput({id: 'gtceu:assembly_line/electric_piston_zpm'}, 'gtceu:osmiridium_rod', 'gtceu:duranium_sleeve')
    event.replaceInput({id: 'gtceu:assembly_line/conveyor_module_uv'}, 'gtceu:tritanium_plate', 'gtceu:tritanium_sleeve')
    event.replaceInput({id: 'gtceu:assembly_line/electric_piston_uv'}, 'gtceu:tritanium_rod', 'gtceu:tritanium_sleeve')
    // event.replaceInput({input: ''}, '', '')
    //#endregion
    
    //#region output
    event.replaceOutput({}, 'ad_extendra:saturlyte_ingot', 'astrogreg:saturlyte_ingot')
    event.replaceOutput({}, 'ad_extendra:juperium_ingot', 'astrogreg:juperium_ingot')
    // event.replaceOutput({output: ''}, '', '')
    //#endregion
});
