ServerEvents.recipes(event => {
    //replace

    //#region input
    event.replaceInput({input: 'create:copper_sheet'}, 'create:copper_sheet', 'gtceu:copper_plate')
    event.replaceInput({input: 'create:zinc_ingot'}, 'create:zinc_ingot', 'gtceu:zinc_ingot')
    event.replaceInput({}, 'botania:redstone_root', 'gtceu:red_alloy_dust')
    event.replaceInput({}, 'ad_astra:steel_rod', 'gtceu:steel_rod')
    event.replaceInput({}, 'ad_astra:iron_rod', 'gtceu:iron_rod')
    event.replaceInput({}, 'minecraft:gravel', '#forge:gravel')
    event.replaceInput({}, 'minecraft:sand', '#forge:sand')
    event.replaceInput({id: 'farmersdelight:roast_chicken_block'}, '#forge:eggs', 'farmersdelight:fried_egg')
    event.replaceInput({id: 'delightful:food/pumpkin_pie'}, '#forge:eggs', 'farmersdelight:fried_egg')
    event.replaceInput({input: 'botania:rune_fire'}, 'botania:rune_fire', 'botania:fire_rune')
    event.replaceInput({input: 'botania:rune_water'}, 'botania:rune_water', 'botania:water_rune')
    event.replaceInput({input: 'botania:rune_air'}, 'botania:rune_air', 'botania:air_rune')
    event.replaceInput({input: 'botania:rune_earth'}, 'botania:rune_earth', 'botania:earth_rune')
    event.replaceInput({input: 'botania:rune_spring'}, 'botania:rune_spring', 'botania:spring_rune')
    event.replaceInput({input: 'botania:rune_summer'}, 'botania:rune_summer', 'botania:summer_rune')
    event.replaceInput({input: 'botania:rune_autumn'}, 'botania:rune_autumn', 'botania:autumn_rune')
    event.replaceInput({input: 'botania:rune_winter'}, 'botania:rune_winter', 'botania:winter_rune')
    event.replaceInput({input: 'botania:rune_mana'}, 'botania:rune_mana', 'botania:mana_rune')
    event.replaceInput({input: 'botania:rune_greed'}, 'botania:rune_greed', 'botania:greed_rune')
    event.replaceInput({input: 'botania:rune_wrath'}, 'botania:rune_wrath', 'botania:wrath_rune')
    event.replaceInput({input: 'botania:rune_pride'}, 'botania:rune_pride', 'botania:pride_rune')
    event.replaceInput({input: 'botania:rune_lust'}, 'botania:rune_lust', 'botania:lust_rune')
    event.replaceInput({input: 'botania:rune_sloth'}, 'botania:rune_sloth', 'botania:sloth_rune')
    event.replaceInput({input: 'botania:rune_gluttony'}, 'botania:rune_gluttony', 'botania:gluttony_rune')
    event.replaceInput({input: 'botania:rune_envy'}, 'botania:rune_envy', 'botania:envy_rune')
    event.replaceInput({output: 'minecraft:brick'}, 'minecraft:clay_ball', 'gtceu:compressed_clay')
    event.replaceInput({input: 'ae2:certus_quartz_crystal'}, 'ae2:certus_quartz_crystal', 'gtceu:certus_quartz_gem')
    event.replaceInput({output: /gtceu:lv_.*/}, 'minecraft:diamond', 'gtceu:grinding_head_damascus_steel')
    event.replaceInput({output: /gtceu:mv_.*/}, 'minecraft:diamond', 'gtceu:grinding_head_damascus_steel')
    event.replaceInput({output: /gtceu:zpm_.*/}, 'gtceu:tungsten_grinding_head', 'gtceu:grinding_head_duranium')
    event.replaceInput({output: /gtceu:uv_.*/}, 'gtceu:tungsten_grinding_head', 'gtceu:grinding_head_duranium')
    event.replaceInput({}, 'gtceu:diamond_grinding_head', 'gtceu:grinding_head_diamond')
    event.replaceInput({}, 'gtceu:tungsten_grinding_head', 'gtceu:grinding_head_tungsten')
    event.replaceInput({}, 'botania:mana_glass', 'botania:managlass')
    event.replaceInput({}, 'botania:elf_glass', 'botania:alfglass')
    event.replaceInput({}, 'ad_extendra:saturlyte_ingot', 'astrogreg:saturlyte_ingot')
    event.replaceInput({}, 'ad_extendra:juperium_ingot', 'astrogreg:juperium_ingot')
    event.replaceInput({output: 'farmersdelight:mixed_salad'}, 'farmersdelight:tomato', 'farmersdelight:tomato_slice')
    event.replaceInput({output: 'farmersdelight:fruit_salad'}, 'minecraft:apple', 'farmersdelight:apple_slice')
    // event.replaceInput({input: ''}, '', '')
    //#endregion
    
    //#region output
    event.replaceOutput({output: 'ae2:certus_quartz_crystal'}, 'ae2:certus_quartz_crystal', 'gtceu:certus_quartz_gem')
    event.replaceOutput({}, 'ad_extendra:saturlyte_ingot', 'astrogreg:saturlyte_ingot')
    event.replaceOutput({}, 'ad_extendra:juperium_ingot', 'astrogreg:juperium_ingot')
    // event.replaceOutput({output: ''}, '', '')
    //#endregion
});
