//#region remove tags

//make sure items, fluids, and blocks go under their respective regions or they won't work



//#region items
ServerEvents.tags('item', event => {
event.removeAllTagsFrom('ad_astra:steel_rod')
event.removeAllTagsFrom('ad_astra:steel_block')
event.removeAllTagsFrom('ad_astra:steel_plate')
event.removeAllTagsFrom('ad_astra:steel_nugget')
event.removeAllTagsFrom('ad_astra:steel_ingot')
event.removeAllTagsFrom('ad_astra:iron_rod')
event.removeAllTagsFrom('ad_astra:iron_plate')
event.removeAllTagsFrom('ad_astra:iron_nugget')
event.removeAllTagsFrom('ad_astra:moon_desh_ore')
event.removeAllTagsFrom('ad_astra:deepslate_desh_ore')
event.removeAllTagsFrom('ad_extendra:raw_plutonium')
event.removeAllTagsFrom('ad_extendra:plutonium_nugget')
event.removeAllTagsFrom('ad_extendra:uraninium_nugget')
event.removeAllTagsFrom('ad_extendra:uraninium_ingot')
event.removeAllTagsFrom('ad_extendra:uraninium_plate')
event.removeAllTagsFrom('ad_extendra:raw_uranium')
event.removeAllTagsFrom('ad_extendra:uranium_ingot')
event.removeAllTagsFrom('ad_extendra:uranium_nugget')
event.removeAllTagsFrom('gtceu:skystone_dust')
event.removeAllTagsFrom('create:iron_plate')
event.removeAllTagsFrom('create:iron_sheet')
event.removeAllTagsFrom('create:brass_sheet')
event.removeAllTagsFrom('create:copper_sheet')
event.removeAllTagsFrom('create:golden_sheet')
event.removeAllTagsFrom('create:brass_ingot')
event.removeAllTagsFrom('create:brass_nugget')
event.removeAllTagsFrom('create:zinc_nugget')
event.removeAllTagsFrom('create:zinc_ingot')
event.removeAllTagsFrom('create:dough')
event.removeAllTagsFrom('create:red_sand_paper')
event.removeAllTagsFrom('createaddition:zinc_sheet')
event.removeAllTagsFrom('createaddition:zinc_nugget')
event.removeAllTagsFrom('createaddition:electrum_sheet')
event.removeAllTagsFrom('createaddition:electrum_nugget')
event.removeAllTagsFrom('createaddition:electrum_ingot')
event.removeAllTagsFrom('createaddition:copper_rod')
event.removeAllTagsFrom('createaddition:gold_rod')
event.removeAllTagsFrom('createaddition:iron_rod')
event.removeAllTagsFrom('createaddition:electrum_rod')
event.removeAllTagsFrom('createaddition:electrum_block')
event.removeAllTagsFrom('createaddition:brass_rod')
event.removeAllTagsFrom('createaddition:diamond_grit')
event.removeAllTagsFrom('createaddition:diamond_grit_sandpaper')
event.removeAllTagsFrom('farmersdelight:wheat_dough')
event.removeAllTagsFrom('powah:uraninite_raw')
event.removeAllTagsFrom(/farmersdelight:.*_knife/)
event.removeAllTagsFrom('gtceu:elementium_ingot')
event.removeAllTagsFrom('gtceu:elementium_nugget')
event.removeAllTagsFrom('gtceu:manasteel_ingot')
event.removeAllTagsFrom('gtceu:manasteel_nugget')
event.removeAllTagsFrom('gtceu:terrasteel_ingot')
event.removeAllTagsFrom('gtceu:terrasteel_nugget')
event.removeAllTagsFrom('gtceu:gaiasteel_ingot')
event.removeAllTagsFrom('gtceu:gaiasteel_nugget')
event.removeAllTagsFrom('gtceu:elementium_block')
event.removeAllTagsFrom('gtceu:manasteel_block')
event.removeAllTagsFrom('gtceu:terrasteel_block')
event.removeAllTagsFrom('gtceu:gaiasteel_block')
event.removeAllTagsFrom('ae2:ender_dust')
event.removeAllTagsFrom('gtceu:mana_diamond_gem')
event.removeAllTagsFrom('gtceu:mana_diamond_block')
event.removeAllTagsFrom('gtceu:dragonstone_gem')
event.removeAllTagsFrom('gtceu:dragonstone_block')
event.removeAllTagsFrom('powah:crystal_niotic')
event.removeAllTagsFrom('powah:crystal_spirited')
event.removeAllTagsFrom('powah:crystal_blazing')
event.removeAllTagsFrom('powah:crystal_nitro')
event.removeAllTagsFrom(/botania:rune_.*/)
event.removeAllTagsFrom('ad_extendra:glacian_sapling')
event.removeAllTagsFrom('create:blaze_cake')
event.removeAllTagsFrom('create:creative_blaze_cake')
event.removeAllTagsFrom('create:blaze_cake_base')
event.removeAllTagsFrom('createaddition:cake_base')
event.removeAllTagsFrom('createaddition:cake_base_baked')
event.removeAllTagsFrom('create:builders_tea')
event.removeAllTagsFrom('createaddition:bioethanol_bucket')
event.removeAllTagsFrom('botania:mana_glass')
event.removeAllTagsFrom('botania:elf_glass')
event.removeAllTagsFrom('botania:mana_glass_pane')
event.removeAllTagsFrom('botania:elf_glass_pane')
event.removeAllTagsFrom('gtceu:wood_plate')
event.removeAllTagsFrom('gtceu:treated_wood_plate')
event.removeAllTagsFrom('ae2:certus_quartz_crystal')
event.removeAllTagsFrom('botania:bifrost_perm')
event.removeAllTagsFrom('create:powdered_obsidian')
event.removeAllTagsFrom('create:sturdy_sheet')
event.removeAllTagsFrom('ad_extendra:uranium_plate')
event.removeAllTagsFrom('ad_extendra:plutonium_ingot')
event.removeAllTagsFrom('ad_extendra:neptunium_ingot')
event.removeAllTagsFrom('ad_astra:wrench')
event.removeAllTagsFrom('powah:wrench')
event.removeAllTagsFrom('ad_extendra:neptunium_nugget')
event.removeAllTagsFrom('ad_extendra:plutonium_block')
event.removeAllTagsFrom('ad_extendra:neptunium_block')
event.removeAllTagsFrom('ae2:certus_quartz_dust')
event.removeAllTagsFrom('ad_extendra:juperium_ingot')
event.removeAllTagsFrom('ad_extendra:juperium_plate')
event.removeAllTagsFrom('ad_extendra:saturlyte_ingot')
event.removeAllTagsFrom('ad_extendra:saturlyte_plate')
event.removeAllTagsFrom('delightful:source_berry_cookie')
event.removeAllTagsFrom(/delightful:.*_knife/)
});



//#region blocks
ServerEvents.tags('block', event => {
event.removeAllTagsFrom('ad_extendra:raw_plutonium_block')
event.removeAllTagsFrom('ad_extendra:plutonium_block' )
event.removeAllTagsFrom('ad_extendra:uraninium_block')
event.removeAllTagsFrom('ad_extendra:raw_uranium_block')
event.removeAllTagsFrom('createaddition:electrum_block')
});



//#region fluids
ServerEvents.tags('fluid', event => {
event.removeAllTagsFrom('ad_astra:hydrogen')
event.removeAllTagsFrom('ad_astra:cryo_fuel')
event.removeAllTagsFrom('ad_astra:oxygen')
event.removeAllTagsFrom('ad_astra:oil')
event.removeAllTagsFrom('ad_astra:fuel')
event.removeAllTagsFrom('createaddition:bioethanol')
event.removeAllTagsFrom('createaddition:seed_oil')
event.remove('create:bottomless/allow', 'minecraft:lava')
event.remove('create:bottomless/allow', 'minecraft:water')
});



//#region add tags




//#region items
ServerEvents.tags('item', event => {
event.add('botania:elvenwood', 'botanicadds:elvenwood')
event.add('botania:elvenwood', 'botanicadds:elvenwood_log')
event.add('minecraft:logs_that_burn', 'botanicadds:elvenwood')
event.add('minecraft:logs_that_burn', 'botanicadds:elvenwood_log')
event.add('minecraft:logs', 'botanicadds:elvenwood')
event.add('minecraft:logs', 'botanicadds:elvenwood_log')
event.add('forge:lenses', 'botania:lens_normal')
event.add('forge:lenses', 'botania:terra_lens')
event.add('forge:lenses', 'botania:pixie_lens')
event.add('forge:lenses', 'botania:gaia_lens')
event.add('forge:rods/wooden', 'botania:livingwood_twig')
event.add('botania:runes', 'botania:air_rune')
event.add('botania:runes', 'botania:fire_rune')
event.add('botania:runes', 'botania:water_rune')
event.add('botania:runes', 'botania:earth_rune')
event.add('botania:runes', 'botania:spring_rune')
event.add('botania:runes', 'botania:summer_rune')
event.add('botania:runes', 'botania:autumn_rune')
event.add('botania:runes', 'botania:winter_rune')
event.add('botania:runes', 'botania:mana_rune')
event.add('botania:runes', 'botania:lust_rune')
event.add('botania:runes', 'botania:gluttony_rune')
event.add('botania:runes', 'botania:greed_rune')
event.add('botania:runes', 'botania:sloth_rune')
event.add('botania:runes', 'botania:wrath_rune')
event.add('botania:runes', 'botania:envy_rune')
event.add('botania:runes', 'botania:pride_rune')
event.add('botania:runes', 'botania:energy_rune')
event.add('botania:runes', 'botania:space_rune')
event.add('botania:runes', 'botania:life_rune')
event.add('botania:runes', 'botania:gaia_rune')
event.add('forge:grass', 'minecraft:grass')
event.add('forge:grass', 'farmersdelight:sandy_shrub')
event.add('forge:grass', 'minecraft:tall_grass')
event.add('forge:fruit_slice', 'minecraft:melon_slice')
event.add('forge:fruit_slice', 'farmersdelight:melon_slice')
event.add('c:glass_panes', 'botania:managlass_pane')
event.add('trashcans:trash_cans', 'trashcans:liquid_trash_can')
event.add('trashcans:trash_cans', 'trashcans:energy_trash_can')
event.add('trashcans:trash_cans', 'trashcans:item_trash_can')
event.add('trashcans:trash_cans', 'trashcans:ultimate_trash_can')
event.add('create:pulpifiable', 'farmersdelight:tree_bark')
event.add('forge:meat', 'minecraft:beef')
event.add('forge:meat', 'minecraft:chicken')
event.add('forge:meat', 'minecraft:mutton')
event.add('forge:meat', 'minecraft:porkchop')
event.add('forge:meat', 'minecraft:rabbit')
event.add('forge:meat', 'delightful:raw_goat')
event.add('forge:meat_small', 'farmersdelight:minced_beef')
event.add('forge:meat_small', 'farmersdelight:chicken_cuts')
event.add('forge:meat_small', 'farmersdelight:bacon')
event.add('forge:meat_small', 'farmersdelight:cod_slice')
event.add('forge:meat_small', 'farmersdelight:salmon_slice')
event.add('forge:meat_small', 'farmersdelight:mutton_chops')
event.add('forge:sweetener', 'minecraft:sugar')
event.add('forge:fruits', 'farmersdelight:apple_slice')
event.add('forge:fruits/sweet', 'farmersdelight:apple_slice')

const tiers = ['ulv', 'lv', 'mv', 'hv', 'ev', 'iv', 'luv', 'zpm', 'uv', 'uhv']
tiers.forEach(tier => {event.add(`gtceu:circuits/${tier}`, `astrogreg:${tier}_modular_circuit`)})
})