StartupEvents.registry('block', event => {

    event.create('astrogreg:asteroid_gravel','falling')
        .translationKey('block.astrogreg.asteroid_gravel')
        .hardness(0.8)
        .resistance(0.8)
        .soundType('gravel')
        .requiresTool(false)
        .tagBoth('forge:gravel')
        .mapColor('terracotta_purple' )
        .tagBlock('mineable/shovel')
        .textureAll('kubejs:block/rocks/asteroid_gravel')
		.fullBlock(true)
		.opaque(true)

    event.create('astrogreg:asteroid_sand','falling')
        .translationKey('block.astrogreg.asteroid_sand')
        .hardness(0.8)
        .resistance(0.8)
        .soundType('sand')
        .requiresTool(false)
        .tagBoth('minecraft:smelts_to_glass')
        .mapColor('terracotta_purple' )
        .tagBlock('mineable/shovel')
        .textureAll('kubejs:block/rocks/asteroid_sand')
		.fullBlock(true)
		.opaque(true)

    event.create('astrogreg:cobbled_asteroid_stone')
        .translationKey('block.astrogreg.cobbled_asteroid_stone')
        .hardness(0.8)
        .resistance(0.8)
        .soundType('stone')
        .requiresTool(true)
        .tagBoth('minecraft:stone_tool_materials')
        .tagBoth('minecraft:stone_crafting_materials')
        .mapColor('terracotta_purple' )
        .tagBlock('mineable/pickaxe')
        .textureAll('kubejs:block/rocks/cobbled_asteroid_stone')
		.fullBlock(true)
		.opaque(true)

    event.create('astrogreg:smooth_asteroid_stone')
        .translationKey('block.astrogreg.smooth_asteroid_stone')
        .hardness(0.8)
        .resistance(0.8)
        .soundType('stone')
        .requiresTool(true)
        .tagBoth('forge:smooth_stone')
        .mapColor('terracotta_purple' )
        .tagBlock('astrogreg:asteroid_stone')
        .tagBlock('mineable/pickaxe')
        .textureAll('kubejs:block/rocks/polished_asteroid_stone')
		.fullBlock(true)
		.opaque(true)
})