StartupEvents.registry('block', event => {
    
    event.create('asteroid_stone')
        .displayName('Asteroid Stone')
        .hardness(0.8)
        .resistance(0.8)
        .soundType('stone')
        .requiresTool(true)
        .tagBoth('forge:stone')
        .mapColor('terracotta_purple' )
        .tagBlock('forge:asteroid_stone')
        .tagBlock('mineable/pickaxe')
        .textureAll('kubejs:block/rocks/asteroid_stone')
		.fullBlock(true)
		.opaque(true);

    event.create('hard_asteroid_stone')
        .displayName('Hard Asteroid Stone')
        .hardness(0.8)
        .resistance(0.8)
        .soundType('stone')
        .requiresTool(true)
        .tagBoth('forge:stone')
        .mapColor('terracotta_purple' )
        .tagBlock('forge:asteroid_stone')
        .tagBlock('mineable/pickaxe')
        .textureAll('kubejs:block/rocks/hard_asteroid_stone')
		.fullBlock(true)
		.opaque(true);

    event.create('asteroid_gravel','falling')
        .displayName('Asteroid Gravel')
        .hardness(0.8)
        .resistance(0.8)
        .soundType('gravel')
        .requiresTool(false)
        .tagBoth('forge:gravel')
        .mapColor('terracotta_purple' )
        .tagBlock('mineable/shovel')
        .textureAll('kubejs:block/rocks/asteroid_gravel')
		.fullBlock(true)
		.opaque(true);

    event.create('asteroid_sand','falling')
        .displayName('Asteroid Sand')
        .hardness(0.8)
        .resistance(0.8)
        .soundType('sand')
        .requiresTool(false)
        .tagBoth('forge:sand')
        .mapColor('terracotta_purple' )
        .tagBlock('mineable/shovel')
        .textureAll('kubejs:block/rocks/asteroid_sand')
		.fullBlock(true)
		.opaque(true);

    event.create('cobbled_asteroid_stone')
        .displayName('Cobbled Asteroid Stone')
        .hardness(0.8)
        .resistance(0.8)
        .soundType('stone')
        .requiresTool(true)
        .tagBoth('minecraft:stone_tool_materials')
        .tagBoth('minecraft:stone_crafting_materials')
        .mapColor('terracotta_purple' )
        .tagBlock('mineable/pickaxe')
        .textureAll('kubejs:block/rocks/cobbled_asteroid_stone')
		.fullBlock(true)
		.opaque(true);

    event.create('smooth_asteroid_stone')
        .displayName('Smooth Asteroid Stone')
        .hardness(0.8)
        .resistance(0.8)
        .soundType('stone')
        .requiresTool(true)
        .tagBoth('forge:smooth_stone')
        .mapColor('terracotta_purple' )
        .tagBlock('astrogreg:asteroid_stone')
        .tagBlock('mineable/pickaxe')
        .textureAll('kubejs:block/rocks/polished_asteroid_stone')
		.fullBlock(true)
		.opaque(true);
})